### ISSUE TITLE
Cruelty to animals

### ISSUE THREAD

**Issue by terrorist96** [liberland/laws#10]
Say you torture a wild animal. How can you be prosecuted for this? The animal cannot consent to your prosecution. It has no owner.

**Comment by Jean-LouisMesic** [comment]
Animal cruelty is indeed an issue, but unprecedented in a Constitution. I'd be interested in pursuing it, though.

**Comment by michalptacnik** [comment]
We will have to have a judicial practice regarding torture of animals and/or laws. Animals are clearly not objects, but they are also not Natural Persons, because they can't ask for their personhood and can't defend it coherently. They are entities capable of feeling pain and possibly, likely of suffering. The judicial practice and/or law within the confines of the constitution will have to define the details. The new Constitution draft allows through our "Commerce Clause" to legislate if there are clearly present serious negative externalities. It is thinkable that those would pertain to animals, not just to humans. Does this make sense?

**Comment by michalptacnik** [comment]
Please reopen the issue if you have more question. We have reviewed the constitution, you can see the new version here: https://docs.google.com/document/d/1RYgEHcb2oMgYJOa2MWUxe8E0aHRIgDpsiMG21MACIVg/edit#heading=h.yur44cl44s61
You can leave there your comments.
