### ISSUE TITLE
rewriting sentencing

### ISSUE THREAD

**Issue by KacperZajc** [liberland/laws#4]
Following my conversation with Jaromir, we are asked to rewrite the sentence section of the Administration of Justice. As you changed it now it is unclear what sentence will be given for what offence.

We want Felonies to be punished by extradition (or imprisonment if the country of origin does not recognise our jurisdiction) and Misdemeanors punished by commonity work and financial restitution to the victim.

Can you edit the document?

**Comment by Arestei** [comment]
The Judge would say which punishment for what as it is written in there. He has a list of punishments and he chooses which one he can use. In previous version there were only two possible punishments for each felony/misdemeanour, which is very limiting.

**Comment by KacperZajc** [comment]
as far as I understand what Jaromir said, we want the sentence of extradition/imprisonment to be strictly limited
plus we need to change 'a)' this gives definition under every offence because you marked 'a' imprisonment sentence and now it look like you give imprisonment for every offence (also Jaromir's remark)

**Comment by Arestei** [comment]
Well in next paragraph there is, that for felony the Judge can use anything he thinks is right and for misdemeanours everything instead of imprisonment. 
Moreover, imprisonment is in most countries basic punishment, witch is not used everytime, it is here just to discourage potential offender from committing the crime. So I see nothing bad in there.

But feel free to change it. I don't see any reason to change it, because still there is a strong Judge who should have the privilige to punish offenders strongly or softly depending on many factors which we cannot describe as the law would be very long...
