### ISSUE TITLE
Restitution in criminal code

### ISSUE THREAD

**Issue by liberty90** [liberland/laws#6]
How much money should victim receive from a sentenced thief ? Kinsella wrote once that even 2:1  compensation ratio may be unjust, not to say anything about 1:1 ratio, which seems to be suggested by the current criminal code (if I understand everything right ?).

"(...) Suppose one in every 36 thiefs gets caught after he commits a crime. When I play a roulette, I bet a dollar on a certain number, and if I win I get 36 bucks. That’s how every insurance agency work, and that’s both fair and economically sound. Now a thief forced me to play the same game with my wallet, but if I win I only get double, instead of 36:1. That’s unfair! I don’t see any justice here, especially since I did not volunteer to play this stupid game in the first place. (...)"

**Comment by liberty90** [comment]
I want to add that Rothbard suggested 2:1 compensation ratio, so opinions differs substantially; but most libertarian scholars agreed that compensations should go beyond 1:1 restitution. Which means: thief should pay me more than he actually stole.

**Comment by terrorist96** [comment]
They should pay back how much they stole, plus any appropriate punitive damages.

**Comment by Jean-LouisMesic** [comment]
The thief owes you no additional restitution than they offended you in property damage, property loss, property theft, and medical and funeral costs of you and any of your dependent persons or estates incurred during the acts. However, they should also owe an equal sum in either servitude and/or payment to the State, plus the costs of trial.

**Comment by terrorist96** [comment]
What about the cost of you being inconvenienced by having to pursue charges against them? You didn't ask to be stolen from, now you have to spend your time/energy seeking restitution.

**Comment by Jean-LouisMesic** [comment]
True.

**Comment by michalptacnik** [comment]
I would generally go with Rothbard. Please keep in mind that Liberland doesn't exist in a vacuum and we will have to have criminal law somewhat similar to other states, especially our neighbours. We must be a good neighbours. But - our constitution will make it impossible to prosecute victimless crimes, and that is a big difference and an improvement. The new draft constitution is here: https://docs.google.com/document/d/1RYgEHcb2oMgYJOa2MWUxe8E0aHRIgDpsiMG21MACIVg/edit#heading=h.yur44cl44s61

Please reopen the issue if you wish to discuss anything here, rather than in the constitution draft itself.
